pub const WINDOW_WIDTH: u32 = 640;
pub const WINDOW_HEIGHT: u32 = 480;
pub const WIDTH: u32 = WINDOW_WIDTH * 3 / 4;
pub const HEIGHT: u32 = WINDOW_HEIGHT;
pub const ENEMY_SIZE: f64 = 8.;
pub const BULLET_SIZE: f64 = 8.;
pub const BULLET_SPEED: f64 = 5.;
pub const MISSILE_SPEED: f64 = 3.;
pub const LIGHT_WIDTH: f64 = 3.;
